# DEFINE ALL CONSTANTS HERE
tick_time = 1
seed = 2001

# THE NUMBER OF CUSTOMERS FOR THE MAS SYSTEM CAN BE SET HERE
numberofcustomer=10

# THE VALUE CAN BE SET TO RUN THE SIMULATION FOR THE SPECIFIED PERIOD
# IN OUR CASE IT RUNS FOR 13 MONTHS IN ORDER TO SIMULATE ONE YEAR OF SALES AS ONE MONTH THERE IS NO SALES.
annum_count=13
